version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - .docker/postgresql/data:/var/lib/postgresql/data
  server:
    build: ./server
    ports: 
      - "3000:3000"
    volumes:
      - server:/usr/src/app
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  web:
    build: ./web
    ports: 
      - "4200:4200"
    volumes:
      - web:/app
    environment:
      - API_HOST=server
volumes:
  db:
    driver: local
  server:
    driver: local
  web:
    driver: local