# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: TravelManager_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: /home/runner/work/TravelManager/TravelManager/server/Gemfile
      DATABASE_USER: rails
      DATABASE_PASSWORD: password
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        working-directory: ./server
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        working-directory: ./server
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: /home/runner/work/TravelManager/TravelManager/server/Gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bin/bundler-audit --update
        working-directory: ./server
      - name: Security audit application code
        run: bin/brakeman -q -w2
        working-directory: ./server
      - name: Lint Ruby files
        run: bin/rubocop --parallel
        working-directory: ./server
